// Objective-C API for talking to github.com/glassmonkey/flutter_with_golang/golang/pkg/api Go package.
//   gobind -lang=objc github.com/glassmonkey/flutter_with_golang/golang/pkg/api
//
// File is generated by gobind. Do not edit.

#ifndef __Api_H__
#define __Api_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT BOOL ApiEvaluate(NSString* _Nullable formula, double* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull ApiGoCall(NSError* _Nullable* _Nullable error);

#endif
