
// Objective-C API for talking to the following Go packages
//
//	github.com/glassmonkey/flutter_with_golang/golang/pkg/api
//
// File is generated by gomobile bind. Do not edit.
#ifndef __API_FRAMEWORK_H__
#define __API_FRAMEWORK_H__

#include "Api.objc.h"
#include "Universe.objc.h"

#endif
